@startuml Trabajo practico

skinparam classAttributeIconSize 0

enum ESTADO_ITEM {
    PENDIENTE
    EN_PREPARACION
    LISTO
}

enum ESTADO_PEDIDO {
    EN_CONSTRUCCION
    CONFIRMADO
    FACTURADO
}

enum MEDIO_DE_PAGO {
    EFECTIVO
    TARJETA_DEBITO
    TARJETA_CREDITO
    BILLETERA_VIRTUAL
}

enum DIA_SEMANA {
    DOMINGO
    LUNES
    MARTES 
    MIERCOLES
    JUEVES
    VIERNES
    SABADO 
}

enum TIPO_ESTACION {
    PARRILLA
    COCINA_FRIA
    BARRA
    COCINA_DULCE
}

class GestorPedidos {
    - pedido: Pedido
    - historialDePedidos: Map<number, Pedido>
    - estaciones: Estacion[]

    + pedidoPago(mp: MediosDePago)
    + getHistorial(): Pedido[]
    + consultarHistorialPedido(numPedido: number): Pedido
    + agregarItem()
    + agregarCombo()
    + eliminarItem()
    + eliminarCombo()
    + confirmarPedido()
    + asignarAEstaciones()
    + facturarPedido()
}

abstract class Pedido {
    - numeroDePedido: number
    - cliente: Cliente
    - items: Item[]
    - combos: Combo[]
    - precioTotal: number
    - medioDePago: MediosDePago | undefined
    - estadoDelPedido: ESTADO_PEDIDO
    - diaActual: DIA_SEMANA

    # abstract pedir()
    # abstract entregar() 
        'mover al mozo o cadete
    + estadoItems(): ESTADO_ITEM
    # calcularPrecio()
    + confirmarPedido()
    - validarPedidoEnConstruccion()
    + facturarPedido()
    + agregarItem(i: Item)
    + agregarCombo(c: Combo)
    + eliminarItem(i: Item)
    + eliminarCombo(c: Combo)

}

class PedidoSalon {
    - mozo: Mozo
    - numeroDeMesa: number
    - pedidoMesaCerrada: boolean
}

class PedidoRetiro {
    - horarioDeRetiro: number
    - numeroDeTelefono: number
    - pedidoRetirado: boolean
}

class PedidoEnvio {
    - direccionDeEntrega: string
    - costoDeEnvio: number
    - cadete: Cadete
    - barrio: string
    - pedidoEntregado: boolean
}

interface MediosDePago {
    + pagoCompletado()
}

abstract class Tarjeta {
    - medioDePago: MediosDePago
    - numeroTarjeta
    - nombreTitular
    - codigoSeguridad
    - fechaVencimiento
    - saldo
}

class TarjetaCredito {

}

class TarjetaDebito {

}

class Efectivo {

}

class BilleteraVirtual {

}

class Cliente {
    - mesaAsignada

    + pagarPedido()
    + pedirPedido()
}

abstract class Empleado {
    - clientes: Cliente
    - pedidos: Pedido

    + cobrarPedido()
}

class Mozo {
    - gestorDePedido: GestorPedidos
}

class Cadete {

}

Class Menu {
    - combos: Combo[]
    - items: Item[]
}

class Combo {
    - items: Item[]
    - precioCombo
    - beneficios: Beneficio
}

class Item {
    - estacion: Estacion
    - estadoDelItem
    - precioIndividual
}

interface Beneficio {
    + calcularBeneficio()
}

class BeneficioPorPorcentaje {

}

class BeneficioPorPrecioFijo {

}

class DescuentoPorPagoEfectivo {
    - porcentajeAplicado
}

class DescuentoPorDiaDeSemana {
    - diasQueAplica
    - porcentajeAplicado
    - precioAplicado
}


abstract class Estacion {
    - items: Item[]

    + preparandoItem()
    + itemFinalizado()
}

class Parrilla {

}

class CocinaFria {
    
}

class Barra {
    
}

class CocinaDulce {
    
}

class CalculoDia {
    - fecha: Date

    + calculoDia(): DIA_SEMANA
}

'relaciones

Pedido <|-l- PedidoSalon
Pedido <|-r- PedidoRetiro
Pedido <|-- PedidoEnvio

CalculoDia <.. Pedido

GestorPedidos o-- Pedido
GestorPedidos *-- Estacion

PedidoSalon *-- Mozo
PedidoEnvio *-- Cadete

Empleado <|-- Mozo
Empleado <|-- Cadete

Estacion <|-r- Parrilla
Estacion <|-- CocinaFria
Estacion <|-u- Barra
Estacion <|-- CocinaDulce

Menu *-- Item
Menu *-- Combo
Combo *-r- Item
Item o-- Estacion

Beneficio <|.. BeneficioPorPorcentaje
Beneficio <|.. BeneficioPorPrecioFijo
Beneficio <|.. DescuentoPorDiaDeSemana
Beneficio <|.r. DescuentoPorPagoEfectivo
'BeneficioPorPorcentaje <|-- DescuentoPorPagoEfectivo

TarjetaCredito <|-- Tarjeta
TarjetaDebito <|-- Tarjeta
MediosDePago <|.. Tarjeta

Efectivo <|.. MediosDePago
BilleteraVirtual <|.. MediosDePago

'dudas

'en el orden en que le fue llegando: en estacion o en pedido
'tenemos muchos enums? (enum de tipo beneficio) -> no confundirnos TIPO DE DATO con ENUMs - validar si tiene sentido tener ENUM y CLASES (caso de metodos de pago)
'que es un "descuento especial" los dias de semana -> nos podemos tomar la libertad de definirlo como queramos
'datos de tarjeta estan de mas -> puede ser, analizar si es realmente necesario
'si la interfaz se puede usar como tipo de dato (MediosDePago) -> si, es un tipo de dato (como clase abstracta)
'interfaz de MediosDePago estaria bien o no es necesaria/deberia ser clase -> depende de nuestra solucion
'unificamos agregar/eliminarItem/Combo() a un tipo Producto -> depende de nuestra solucion

'pendientes - revisar diagrama

'flechas invertidas: TarjetaCredito/TarjetaDebito con Tarjeta (herencia), Efectivo/BilleteraVirtual con MediosDePago (realizacion)
'revisar composiciones: PedidoSalon-Mozo, PedidoEnvio-Cadete, GestorPedidos-Estacion (llegan por constructor), Item con 2 duenios (Menu y Combo)
'decidir que asociaciones dibujar (el atributo tipado ya expresa la relacion) y ordenar layout (package, together, direcciones)
'visibilidad: GestorPedidos asignarAEstaciones (-)
'Tarjeta tiene atributo medioDePago y ademas implementa MediosDePago -> redundante?

@enduml